spring:
  application:
    name: stock-price-producer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
management:
  endpoints:
    web:
      exposure:
        include: prometheus

app:
  period-ms: 1000
  tickers:
    AMZN: data/AMZN.csv
    APPL: data/APPL.csv
    IBM: data/IBM.csv
    GOOG: data/GOOG.csv
    GOOGL: data/GOOGL.csv
    META: data/META.csv
    MSFT: data/MSFT.csv
    NVDA: data/NVDA.csv
    UNH: data/UNH.csv
    XOM: data/XOM.csv
