spring:
  main:
    web-application-type: none
  application:
    name: stock-price-topology
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
management:
  endpoints:
    web:
      exposure:
        include: prometheus