spring:
  main:
    web-application-type: none
  application:
    name: stock-price-topology
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: stock-price
      replication-factor: 2