services:
#  kafka:
#    image: lensesio/box:latest
#    environment:
#      - EULA=https://licenses.lenses.io/download/lensesdl?id=222e0e4c-0643-11ee-8f1e-42010af01003
#      - ADV_HOST=127.0.0.1
#      - SAMPLEDATA=0
#      - RUNTESTS=0
#    ports:
#      - 3030:3030
#      - 9092:9092
#      - 8081:8081
#    healthcheck:
#      test: nc -z localhost 9092 || exit -1
#      start_period: 15s
#      interval: 5s
#      timeout: 10s
#      retries: 10

  kafka:
    image: landoop/fast-data-dev:latest
    environment:
      - ADV_HOST=127.0.0.1
      - SAMPLEDATA=0
      - RUNTESTS=0
    ports:
      - 3030:3030
      - 9092:9092
      - 8081:8081
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

#  stock-price-producer:
#    image: whalebig27/stock-price-producer:latest
#    depends_on:
#      kafka:
#        condition: service_healthy
#    network_mode: host

#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    environment:
#      - DYNAMIC_CONFIG_ENABLED=true
#    ports:
#      - 8080:8080

