services:
  kafka:
    image: landoop/fast-data-dev:latest
    environment:
      - ADV_HOST=127.0.0.1
      - SAMPLEDATA=0
      - RUNTESTS=0
    ports:
      - 3030:3030
      - 9092:9092
      - 8081:8081

#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    environment:
#      - DYNAMIC_CONFIG_ENABLED=true
#    ports:
#      - 8080:8080

